# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name:')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Chanel:')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=20, verbose_name='Name SubCategory:')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importcsv.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importcsv.Channel'),
        ),
    ]
