# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0003_auto_20170710_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='importcsv.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name Channel:'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description:'),
        ),
    ]
