# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0005_auto_20170710_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='id',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subunlimited',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='importcsv.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Name Channel:'),
        ),
    ]
