# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0007_remove_subcategory_subunlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name Channel:'),
        ),
    ]
