# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0009_auto_20170712_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='sub_category',
        ),
    ]
